version: '2'
services:
  mongors1n1:
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    links:
      - mongors1n2
      - mongors1n3
    volumes:
      - ./data/mongors1n1:/data/db
    networks:
      main:
  mongors1n2:
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    # links:
    #   - mongos1
    volumes:
      - ./data/mongors1n2:/data/db
    networks:
      main:
  mongors1n3:
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    # links:
    #   - mongos1
    volumes:
      - ./data/mongors1n3:/data/db
    networks:
      main:
  mongors2n1:
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    links:
      - mongors2n2
      - mongors2n3
    volumes:
      - ./data/mongors2n1:/data/db
    networks:
      main:
  mongors2n2:
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    # links:
    #   - mongos2
    volumes:
      - ./data/mongors2n2:/data/db
    networks:
      main:
  mongors2n3:
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    # links:
    #   - mongos2
    volumes:
      - ./data/mongors2n3:/data/db
    networks:
      main:
  mongocfg1:
    hostname: mongocfg1
    container_name: mongocfg1
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    # links:
    #   - "mongocfg2:mongocfg3"
    volumes:
      - ./data/mongo-cfg-1:/data/db
    networks:
      main:
        aliases:
          - mongocfg1
  mongocfg2:
    hostname: mongocfg2
    container_name: mongocfg2
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    # links:
    #   - "mongocfg1:mongocfg3"
    volumes:
      - ./data/mongo-cfg-2:/data/db
    networks:
      main:
        aliases:
          - mongocfg2
  mongocfg3:
    hostname: mongocfg3
    container_name: mongocfg3
    image: mongo:3.0.6
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    # links:
    #   - "mongocfg1:mongocfg2"
    volumes:
      - ./data/mongo-cfg-3:/data/db
    networks:
      main:
        aliases:
          - mongocfg3
  mongos1:
    image: mongo:3.0.6
    command: mongos --configdb mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    environment:
      TERM: xterm
    links:
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongors1n1
      - mongors1n2
      - mongors1n3
      - mongors2n1
      - mongors2n2
      - mongors2n3
    ports:
      - 27017:27017
    networks:
      main:
  mongos2:
    image: mongo:3.0.6
    command: mongos --configdb mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    environment:
      TERM: xterm
    links:
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongors1n1
      - mongors1n2
      - mongors1n3
      - mongors2n1
      - mongors2n2
      - mongors2n3
    ports:
      - 27018:27017
    networks:
      main:

networks:
  main: